CREATE TABLE CLIENTE (
    ID              BIGINT       DEFAULT NEXTVAL('SEQ_CLIENTE'),
    NOME_COMPLETO   VARCHAR(255) NOT NULL,
    CPF             VARCHAR(11)  ,
    DATA_NASCIMENTO DATE         NOT NULL,
    ST_CIVIL        CHAR(1)      ,
    RENDA_MENSAL    NUMERIC(11,2),
    E_MAIL          VARCHAR(255) NOT NULL,
    ABERTURA_CONTA  DATE         ,

    CONSTRAINT PK$CLIENTE        PRIMARY KEY(ID),
    CONSTRAINT UK$CLIENTE$CPF    UNIQUE(CPF)    ,
    CONSTRAINT CK$CLIENTE$STATUS CHECK(ST_CIVIL IN ('1','2','3','4'))
);

COMMENT ON COLUMN CLIENTE.ST_CIVIL       IS '1.:SOLTEIRO(A) / 2.:CASADO(A) / 3.:VIUVO(A) / 4.:DIVOCIADO(A)';
COMMENT ON COLUMN CLIENTE.ABERTURA_CONTA IS 'DATA EM QUE A CONTA FOI ABERTA';