CREATE TABLE CLIENTE (
    ID              BIGINT       DEFAULT NEXTVAL('SEQ_CLIENTE'),
    NOME            VARCHAR(255) NOT NULL,
    CPF             VARCHAR(11)  ,
    DATA_NASCIMENTO DATE         NOT NULL,
    ST_CIVIL        CHAR(1)      ,
    RENDA_MENSAL    NUMERIC(11,2),

    CONSTRAINT PK$CLIENTE        PRIMARY KEY(ID),
    CONSTRAINT UK$CLIENTE$CPF    UNIQUE(CPF)    ,
    CONSTRAINT CK$CLIENTE$STATUS CHECK(ST_CIVIL IN ('1','2','3','4','5'))
);