CREATE TABLE PROPOSTA_CREDITO (
    ID             BIGINT        DEFAULT NEXTVAL('SEQ_PROPOSTA_CREDITO'),
    DATA           DATE          NOT NULL,
    VALOR_APROVADO NUMERIC(11,2) NOT NULL,
    STATUS         CHAR(1)       ,
    FK_CLIENTE     BIGINT        NOT NULL,

    CONSTRAINT PK$PROPOSTA_CREDITO         PRIMARY KEY(ID),
    CONSTRAINT CK$PROPOSTA_CREDITO$STATUS  CHECK(STATUS IN ('1','2','3','4')),
    CONSTRAINT FK$CLIENTE$PROPOSTA_CREDITO FOREIGN KEY(FK_CLIENTE) REFERENCES CLIENTE(ID)
);

COMMENT ON COLUMN PROPOSTA_CREDITO.STATUS IS '1.:PENDENTE / 2.:APROVADA / 3.:CANCELADA';